### ISSUE TITLE
修改 ready 为异步获取数据，导致偶尔出现图表渲染不出来的问题。

### ISSUE THREAD

**Issue by weineel** [mpvue/examples#1]
通过延长延时时间可以减少出现问题的概率。

**Comment by anchengjian** [comment]
你好，可以把这个 issue 移到 https://github.com/Meituan-Dianping/mpvue/issues 这里么，我们想保持一个地方进行 issue 沉淀，方便大家以后搜索和查找，这个仓库的 issue 昨天忘记关闭了，感谢。

**Comment by weineel** [comment]
好的
